/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package candy.fabric;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer-Aspire
 */
public class EntryForm extends javax.swing.JFrame {

    /**
     * Creates new form EntryForm
     */
    public EntryForm() {
        initComponents();
        getContentPane().setBackground(new Color( 59 , 63 , 66));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldForUserId = new javax.swing.JTextField();
        labelForUserID = new javax.swing.JLabel();
        labelForPassword = new javax.swing.JLabel();
        buttonForLogIn = new javax.swing.JButton();
        buttonForDefaultAccount = new javax.swing.JButton();
        labelForNameOfFabric = new javax.swing.JLabel();
        passwordFieldForPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textFieldForUserId.setBackground(new java.awt.Color(204, 204, 204));
        textFieldForUserId.setText("18782");
        textFieldForUserId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldForUserIdMouseClicked(evt);
            }
        });

        labelForUserID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelForUserID.setForeground(new java.awt.Color(204, 204, 204));
        labelForUserID.setText("User ID");

        labelForPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelForPassword.setForeground(new java.awt.Color(204, 204, 204));
        labelForPassword.setText("Password");

        buttonForLogIn.setBackground(new java.awt.Color(73, 77, 78));
        buttonForLogIn.setForeground(new java.awt.Color(204, 204, 204));
        buttonForLogIn.setText("Log in");
        buttonForLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForLogInActionPerformed(evt);
            }
        });

        buttonForDefaultAccount.setBackground(new java.awt.Color(73, 77, 78));
        buttonForDefaultAccount.setForeground(new java.awt.Color(204, 204, 204));
        buttonForDefaultAccount.setText("Default Account");
        buttonForDefaultAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForDefaultAccountActionPerformed(evt);
            }
        });

        labelForNameOfFabric.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        labelForNameOfFabric.setForeground(new java.awt.Color(204, 204, 204));
        labelForNameOfFabric.setText("Fabric Management System");

        passwordFieldForPassword.setBackground(new java.awt.Color(204, 204, 204));
        passwordFieldForPassword.setText("alloallo");
        passwordFieldForPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldForPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonForLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(buttonForDefaultAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelForUserID)
                            .addComponent(labelForPassword))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldForUserId)
                            .addComponent(passwordFieldForPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addComponent(labelForNameOfFabric)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelForNameOfFabric)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForUserID)
                    .addComponent(textFieldForUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForPassword)
                    .addComponent(passwordFieldForPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonForDefaultAccount)
                    .addComponent(buttonForLogIn))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonForLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForLogInActionPerformed
        // TODO add your handling code here:
       
 DatabaseConnection dbc = new DatabaseConnection();
        
        String query = "SELECT StuffID,  StuffType, Password FROM StuffTable WHERE StuffID = '"+textFieldForUserId.getText()+"'";
        ResultSet resultSet = dbc.getData(query);
        if(textFieldForUserId.getText().equals("admin")){
             String passTextFromJframe = new String(passwordFieldForPassword.getPassword());
             if(passTextFromJframe.equals("admin")){
                 openMain();
             }
        }else{
            try {
            while(resultSet.next()){
             int usernameFromDatabase= resultSet.getInt("StuffID");
              String passwordFromDatabase = resultSet.getString("Password");
              if(usernameFromDatabase==Integer.parseInt(textFieldForUserId.getText())){
                  
                  String passTextFromJframe = new String(passwordFieldForPassword.getPassword());
                  if(passwordFromDatabase.equals(passTextFromJframe)){
                        openMain();
                  }
              }else{
                  JOptionPane.showMessageDialog(null, "Sorry! your Stuff ID or password entered wrong\nPlease re-enter them");
              }
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(EntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e ){
           JOptionPane.showMessageDialog(null, "There is no such user in our system!");
        }
            
        }
        
        
        
    }//GEN-LAST:event_buttonForLogInActionPerformed

    private void buttonForDefaultAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForDefaultAccountActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "The superadmin account info\nusername - admin\npassword - admin");
    }//GEN-LAST:event_buttonForDefaultAccountActionPerformed

    private void textFieldForUserIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldForUserIdMouseClicked
        // TODO add your handling code here:
        if(textFieldForUserId.getText().equals("18782"))
        {
            textFieldForUserId.setText("");
            textFieldForUserId.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textFieldForUserIdMouseClicked

    private void passwordFieldForPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldForPasswordMouseClicked
        // TODO add your handling code here:
        String passTextFromJframe = new String(passwordFieldForPassword.getPassword());
        if(passTextFromJframe.equals("alloallo"))
        {
            passwordFieldForPassword.setText("");
            passwordFieldForPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passwordFieldForPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm().setVisible(true);
            }
        });
    }
private void openMain(){
    JOptionPane.showMessageDialog(null, "You have entered successfully!");
    MainFrame mainFrame = new MainFrame();
                        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        mainFrame.pack();
                        mainFrame.setLocationRelativeTo(null);
                        mainFrame.setVisible(true);
                        super.dispose();
                         
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonForDefaultAccount;
    private javax.swing.JButton buttonForLogIn;
    private javax.swing.JLabel labelForNameOfFabric;
    private javax.swing.JLabel labelForPassword;
    private javax.swing.JLabel labelForUserID;
    private javax.swing.JPasswordField passwordFieldForPassword;
    private javax.swing.JTextField textFieldForUserId;
    // End of variables declaration//GEN-END:variables
}
