/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package candy.fabric;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;



public class StaffManage extends javax.swing.JFrame {

    /**
     * Creates new form StaffManage
     */
    public StaffManage() {
        initComponents();
        
             getContentPane().setBackground(new Color( ContainerClass.valOne , ContainerClass.valTwo , ContainerClass.valThree));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        buttonForCreate = new javax.swing.JButton();
        buttonForSearch = new javax.swing.JButton();
        buttonForDelete = new javax.swing.JButton();
        buttonForUpdate = new javax.swing.JButton();
        buttonForShowAllStuff = new javax.swing.JButton();
        labelForRirstName = new javax.swing.JLabel();
        labelForLastName = new javax.swing.JLabel();
        jTextForFirstName = new javax.swing.JTextField();
        jTextForLastName = new javax.swing.JTextField();
        labelForID = new javax.swing.JLabel();
        jTextForID = new javax.swing.JTextField();
        jTextForDateOfBirth = new javax.swing.JTextField();
        labelForDateOfBirth = new javax.swing.JLabel();
        dateFormatLabel = new javax.swing.JLabel();
        labelForPassportNumber = new javax.swing.JLabel();
        jTextForPassport = new javax.swing.JTextField();
        labelForEmail = new javax.swing.JLabel();
        jTextForEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        jComboToSelecType = new javax.swing.JComboBox<>();
        jLabelForStuffType = new javax.swing.JLabel();
        jLabelForPassword = new javax.swing.JLabel();
        jPassFieldForPassword = new javax.swing.JPasswordField();
        jLabelForPasswordConfirm = new javax.swing.JLabel();
        jPasswordFieldForPassworkConfirm = new javax.swing.JPasswordField();
        jLabelForMessages = new javax.swing.JLabel();
        jTextForMessages = new javax.swing.JTextField();
        buttonForBack = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stuff Managment");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(59, 63, 66));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonForCreate.setBackground(new java.awt.Color(73, 77, 78));
        buttonForCreate.setForeground(new java.awt.Color(204, 204, 204));
        buttonForCreate.setText("Add Stuff");
        buttonForCreate.setPreferredSize(new java.awt.Dimension(82, 35));
        buttonForCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForCreateActionPerformed(evt);
            }
        });

        buttonForSearch.setBackground(new java.awt.Color(73, 77, 78));
        buttonForSearch.setForeground(new java.awt.Color(204, 204, 204));
        buttonForSearch.setText("Search Stuff");
        buttonForSearch.setToolTipText("");
        buttonForSearch.setPreferredSize(new java.awt.Dimension(82, 35));
        buttonForSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForSearchActionPerformed(evt);
            }
        });

        buttonForDelete.setBackground(new java.awt.Color(73, 77, 78));
        buttonForDelete.setForeground(new java.awt.Color(204, 204, 204));
        buttonForDelete.setText("Delete Stuff");
        buttonForDelete.setPreferredSize(new java.awt.Dimension(82, 35));
        buttonForDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForDeleteActionPerformed(evt);
            }
        });

        buttonForUpdate.setBackground(new java.awt.Color(73, 77, 78));
        buttonForUpdate.setForeground(new java.awt.Color(204, 204, 204));
        buttonForUpdate.setText("Update Stuff");
        buttonForUpdate.setActionCommand("S");
        buttonForUpdate.setPreferredSize(new java.awt.Dimension(82, 35));
        buttonForUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForUpdateActionPerformed(evt);
            }
        });

        buttonForShowAllStuff.setBackground(new java.awt.Color(73, 77, 78));
        buttonForShowAllStuff.setForeground(new java.awt.Color(204, 204, 204));
        buttonForShowAllStuff.setText("Show All Stuff");
        buttonForShowAllStuff.setPreferredSize(new java.awt.Dimension(82, 35));
        buttonForShowAllStuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForShowAllStuffActionPerformed(evt);
            }
        });

        labelForRirstName.setForeground(new java.awt.Color(204, 204, 204));
        labelForRirstName.setText("First Name");

        labelForLastName.setForeground(new java.awt.Color(204, 204, 204));
        labelForLastName.setText("Last Name");

        jTextForFirstName.setBackground(new java.awt.Color(204, 204, 204));
        jTextForFirstName.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextForFirstName.setForeground(new java.awt.Color(0, 153, 153));
        jTextForFirstName.setText("Alisher");
        jTextForFirstName.setToolTipText("");
        jTextForFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextForFirstNameMouseClicked(evt);
            }
        });
        jTextForFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextForFirstNameActionPerformed(evt);
            }
        });

        jTextForLastName.setBackground(new java.awt.Color(204, 204, 204));
        jTextForLastName.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextForLastName.setForeground(new java.awt.Color(0, 153, 153));
        jTextForLastName.setText("Aliev");
        jTextForLastName.setToolTipText("");
        jTextForLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextForLastNameMouseClicked(evt);
            }
        });

        labelForID.setBackground(new java.awt.Color(59, 63, 66));
        labelForID.setForeground(new java.awt.Color(204, 204, 204));
        labelForID.setText("ID");

        jTextForID.setEditable(false);
        jTextForID.setBackground(new java.awt.Color(204, 204, 204));
        jTextForID.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextForID.setForeground(new java.awt.Color(0, 153, 153));
        jTextForID.setText("777");
        jTextForID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextForIDMouseClicked(evt);
            }
        });
        jTextForID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextForIDActionPerformed(evt);
            }
        });

        jTextForDateOfBirth.setBackground(new java.awt.Color(204, 204, 204));
        jTextForDateOfBirth.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextForDateOfBirth.setForeground(new java.awt.Color(0, 153, 153));
        jTextForDateOfBirth.setText("01091984");
        jTextForDateOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextForDateOfBirthMouseClicked(evt);
            }
        });
        jTextForDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextForDateOfBirthActionPerformed(evt);
            }
        });

        labelForDateOfBirth.setForeground(new java.awt.Color(204, 204, 204));
        labelForDateOfBirth.setText("Date of Birth");

        dateFormatLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        dateFormatLabel.setForeground(new java.awt.Color(0, 153, 153));
        dateFormatLabel.setText("Date format: DDMMYYYY");

        labelForPassportNumber.setForeground(new java.awt.Color(204, 204, 204));
        labelForPassportNumber.setText("Passport Number");

        jTextForPassport.setBackground(new java.awt.Color(204, 204, 204));
        jTextForPassport.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextForPassport.setForeground(new java.awt.Color(0, 153, 153));
        jTextForPassport.setText("AA2551232");
        jTextForPassport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextForPassportMouseClicked(evt);
            }
        });
        jTextForPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextForPassportActionPerformed(evt);
            }
        });

        labelForEmail.setForeground(new java.awt.Color(204, 204, 204));
        labelForEmail.setText("Email Adress");

        jTextForEmail.setBackground(new java.awt.Color(204, 204, 204));
        jTextForEmail.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jTextForEmail.setForeground(new java.awt.Color(0, 153, 153));
        jTextForEmail.setText("alisher22@gmail.com");
        jTextForEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextForEmailMouseClicked(evt);
            }
        });
        jTextForEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextForEmailActionPerformed(evt);
            }
        });

        infoTable.setBackground(new java.awt.Color(73, 77, 78));
        infoTable.setForeground(new java.awt.Color(204, 204, 204));
        infoTable.setModel(tableModel);
        infoTable.setSelectionForeground(new java.awt.Color(204, 0, 153));
        infoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(infoTable);

        jComboToSelecType.setBackground(new java.awt.Color(73, 77, 78));
        jComboToSelecType.setForeground(new java.awt.Color(204, 204, 204));
        jComboToSelecType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Worker", "Owner" }));
        jComboToSelecType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboToSelecTypeActionPerformed(evt);
            }
        });

        jLabelForStuffType.setForeground(new java.awt.Color(204, 204, 204));
        jLabelForStuffType.setText("Staff Type");

        jLabelForPassword.setForeground(new java.awt.Color(204, 204, 204));
        jLabelForPassword.setText("Password");

        jPassFieldForPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPassFieldForPassword.setText("jPasswordField1");
        jPassFieldForPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPassFieldForPasswordMouseClicked(evt);
            }
        });
        jPassFieldForPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassFieldForPasswordActionPerformed(evt);
            }
        });

        jLabelForPasswordConfirm.setForeground(new java.awt.Color(204, 204, 204));
        jLabelForPasswordConfirm.setText("Confirm Password");

        jPasswordFieldForPassworkConfirm.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordFieldForPassworkConfirm.setText("jPasswordField2");
        jPasswordFieldForPassworkConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldForPassworkConfirmMouseClicked(evt);
            }
        });

        jLabelForMessages.setForeground(new java.awt.Color(204, 204, 204));
        jLabelForMessages.setText("Messages");

        jTextForMessages.setEditable(false);
        jTextForMessages.setBackground(new java.awt.Color(204, 204, 204));
        jTextForMessages.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextForMessages.setForeground(new java.awt.Color(153, 255, 102));
        jTextForMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextForMessagesActionPerformed(evt);
            }
        });

        buttonForBack.setBackground(new java.awt.Color(73, 77, 78));
        buttonForBack.setForeground(new java.awt.Color(204, 204, 204));
        buttonForBack.setText("Back ");
        buttonForBack.setPreferredSize(new java.awt.Dimension(82, 35));
        buttonForBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelForPassportNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelForRirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelForID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelForDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelForLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelForEmail))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextForDateOfBirth, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextForPassport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jTextForEmail)
                            .addComponent(jTextForFirstName)
                            .addComponent(jTextForID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextForLastName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelForStuffType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelForPassword)
                                    .addComponent(jLabelForPasswordConfirm))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelForMessages)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextForMessages))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboToSelecType, 0, 149, Short.MAX_VALUE)
                        .addComponent(jPassFieldForPassword)
                        .addComponent(jPasswordFieldForPassworkConfirm))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonForSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonForShowAllStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonForBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonForCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonForUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonForDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForID)
                    .addComponent(jTextForID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelForStuffType)
                    .addComponent(jComboToSelecType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForRirstName)
                    .addComponent(jTextForFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelForPassword)
                    .addComponent(jPassFieldForPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelForLastName))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelForPasswordConfirm)
                            .addComponent(jPasswordFieldForPassworkConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextForLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateFormatLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(labelForDateOfBirth)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextForDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextForPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelForPassportNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextForEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelForEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelForMessages)
                            .addComponent(jTextForMessages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonForCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForShowAllStuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonForUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForUpdateActionPerformed
        // TODO add your handling code here:

  int selectedRow = infoTable.getSelectedRow();
             String selectedID = String.valueOf(infoTable.getValueAt(selectedRow, 0));
             
     
      DatabaseConnection databaseConnection = new DatabaseConnection();
      try{
      String  query= "UPDATE StuffTable SET StuffID='"+Integer.parseInt(jTextForID.getText())+"'"
              + ",FirstName='"+jTextForFirstName.getText()+"',LastName='"+jTextForLastName.getText()+"', PassportNumber='"+jTextForPassport.getText()+"'"
              + ",dateOfBirth='"+jTextForDateOfBirth.getText()+"',EmailAddress='"+jTextForEmail.getText()+"'"
              + ",StuffType='"+jComboToSelecType.getSelectedItem().toString()+"' WHERE StuffID ='"+selectedID+"'";
      
        databaseConnection.updateData(query);
        } catch (Exception e) {
            e.printStackTrace();
        }
  
       showTableResult();
        makeFormEmpty();
        jTextForMessages.setText("Stuff updated successfully");
    }//GEN-LAST:event_buttonForUpdateActionPerformed

    private void buttonForCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForCreateActionPerformed
        // TODO add your handling code here:
       addStuff();
    }//GEN-LAST:event_buttonForCreateActionPerformed

    private void jTextForFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextForFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextForFirstNameActionPerformed

    private void jTextForDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextForDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextForDateOfBirthActionPerformed

    private void jTextForEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextForEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextForEmailActionPerformed

    private void buttonForShowAllStuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForShowAllStuffActionPerformed
                // TODO add your handling code here:
   showTableResult();
   jTextForMessages.setText("All show showed");
    }//GEN-LAST:event_buttonForShowAllStuffActionPerformed

    private void jTextForPassportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextForPassportMouseClicked
        // TODO add your handling code here:
        if(jTextForPassport.getText().equals("AA2551232"))
        {
            jTextForPassport.setText("");
            jTextForPassport.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextForPassportMouseClicked

    private void jTextForPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextForPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextForPassportActionPerformed

    private void jTextForDateOfBirthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextForDateOfBirthMouseClicked
        // TODO add your handling code here:
         if(jTextForDateOfBirth.getText().equals("01091984"))
        {
            jTextForDateOfBirth.setText("");
            jTextForDateOfBirth.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextForDateOfBirthMouseClicked

    private void jTextForLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextForLastNameMouseClicked
        // TODO add your handling code here:
         if(jTextForLastName.getText().equals("Aliev"))
        {
            jTextForLastName.setText("");
            jTextForLastName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextForLastNameMouseClicked

    private void jTextForFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextForFirstNameMouseClicked
        // TODO add your handling code here:
          if(jTextForFirstName.getText().equals("Alisher"))
        {
            jTextForFirstName.setText("");
            jTextForFirstName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextForFirstNameMouseClicked

    private void jTextForIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextForIDMouseClicked
        // TODO add your handling code here:
         if(jTextForID.getText().equals("777"))
        {
            jTextForID.setText("");
            jTextForID.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextForIDMouseClicked

    private void jTextForEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextForEmailMouseClicked
        // TODO add your handling code here:
         if(jTextForEmail.getText().equals("alisher22@gmail.com"))
        {
            jTextForEmail.setText("");
            jTextForEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextForEmailMouseClicked

    private void buttonForSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForSearchActionPerformed
        // TODO add your handling code here:
         DatabaseConnection dbc = new DatabaseConnection();
        
        String query = "SELECT StuffID, FirstName, LastName, StuffType FROM StuffTable WHERE StuffID = '"+jTextForID.getText()+"'";
        ResultSet resultSet = dbc.getData(query);
        
        try
        {
          
            int i=0;
            
                while (resultSet.next()) 
                {
                    Object[] row = { null, null, null,null};
                    tableModel.addRow(row);
                    infoTable.setValueAt(resultSet.getString(1), i, 0);
                    infoTable.setValueAt(resultSet.getString(2), i, 1);
                    infoTable.setValueAt(resultSet.getString(3), i, 2);
                    infoTable.setValueAt(resultSet.getString(4), i, 3);
                    i++;

                    jTextForMessages.setText("Stuff found");
                }
                    
        }
        catch(SQLException e)
        {
                System.out.println(e);
        } 
    }//GEN-LAST:event_buttonForSearchActionPerformed

    private void buttonForDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRow = infoTable.getSelectedRow();
        String selectedID = String.valueOf(infoTable.getValueAt(selectedRow, 0));
        
        System.out.println("Row Selection: "+selectedRow);
        System.out.println("Stuff ID: "+selectedID);
        
        String query="Delete * from StuffTable WHERE StuffID='"+selectedID+"'";
	new DatabaseConnection().deleteData(query);
        
        tableModel.removeRow(selectedRow);
        infoTable.repaint();
        jTextForMessages.setText("Stuff deleted successfully");
    }//GEN-LAST:event_buttonForDeleteActionPerformed

    private void infoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoTableMouseClicked
        // TODO add your handling code here:
          DatabaseConnection databaseConnection = new DatabaseConnection();
        int selectedRow = infoTable.getSelectedRow();
        try {
             String selectedID = String.valueOf(infoTable.getValueAt(selectedRow, 0));
              String query = "SELECT StuffID, FirstName, LastName,PassportNumber,DateOfBirth, EmailAddress FROM StuffTable WHERE StuffID = '"+selectedID+"'";
        ResultSet resultSet = databaseConnection.getData(query);
       
            while(resultSet.next()){
                jTextForID.setText(resultSet.getString("StuffID")); 
                jTextForPassport.setText(resultSet.getString("PassportNumber")); 
              jTextForFirstName.setText(resultSet.getString("FirstName"));  
              jTextForLastName.setText(resultSet.getString("LastName"));
              jTextForDateOfBirth.setText(resultSet.getString("DateOfBirth")); 
              jTextForEmail.setText(resultSet.getString("EmailAddress"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }catch(NullPointerException e){
            System.out.println("You have selected empty row");
        }
    }//GEN-LAST:event_infoTableMouseClicked

    private void jComboToSelecTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboToSelecTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboToSelecTypeActionPerformed

    private void jPassFieldForPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassFieldForPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassFieldForPasswordActionPerformed

    private void jPassFieldForPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassFieldForPasswordMouseClicked
        // TODO add your handling code here:
        jPassFieldForPassword.setText("");
    }//GEN-LAST:event_jPassFieldForPasswordMouseClicked

    private void jPasswordFieldForPassworkConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldForPassworkConfirmMouseClicked
        // TODO add your handling code here:
           jPasswordFieldForPassworkConfirm.setText("");
    }//GEN-LAST:event_jPasswordFieldForPassworkConfirmMouseClicked

    private void buttonForBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForBackActionPerformed
        // TODO add your handling code here:
          MainFrame mainFrame = new MainFrame();
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       mainFrame.pack();
    mainFrame.setLocationRelativeTo(null);
    mainFrame.setVisible(true);
    super.dispose();
    
    }//GEN-LAST:event_buttonForBackActionPerformed

    private void jTextForIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextForIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextForIDActionPerformed

    private void jTextForMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextForMessagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextForMessagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffManage().setVisible(true);
            }
        });
    }
javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "StuffID", "FirstName", "LastName","StuffType"
            }
        );
private void showTableResult(){
 tableModel.setRowCount(0);
    DatabaseConnection databaseConnection =new DatabaseConnection();
    String query = "SELECT StuffID, FirstName, LastName, StuffType FROM StuffTable";
        ResultSet resultSet = databaseConnection.getData(query);
        
        infoTable.repaint();

       
       // System.out.println(infoTable.getRowCount());
        for(int i=0; i<infoTable.getRowCount();i++)
        {
            tableModel.removeRow(i);
        }
                
        try
        {
            //m.out.println("Stuff ID\tFirst Name\tLast Name\tStuffType");
            int i=0;
            
                while (resultSet.next()) 
                {
                    Object[] row = { null, null, null,null};
                    tableModel.addRow(row);
                    infoTable.setValueAt(resultSet.getString(1), i, 0);
                    infoTable.setValueAt(resultSet.getString(2), i, 1);
                    infoTable.setValueAt(resultSet.getString(3), i, 2);
                    infoTable.setValueAt(resultSet.getString(4), i, 3);
                    i++;
//System.out.println(resultSet.getString(1)+"\t"+resultSet.getString(2)+"\t"+resultSet.getString(3));
                }
                    
        }
        catch(SQLException e)
        {
                System.out.println(e);
        }
        finally{
            resultSet=null;
        }
}

private void makeFormEmpty() {
      jTextForID.setText(""); 
                jTextForPassport.setText("");
              jTextForFirstName.setText("") ;
              jTextForLastName.setText("");
              jTextForDateOfBirth.setText("");
              jTextForEmail.setText("");   
    }

private void addStuff(){
     String stuffTypeString = jComboToSelecType.getSelectedItem().toString();
    String passTextOriginal = new String(jPassFieldForPassword.getPassword());
     String passTextCopy = new String(jPasswordFieldForPassworkConfirm.getPassword());
       
        if(passTextOriginal.equals(passTextCopy)){
             DateOfBirth dateOfBirth = new DateOfBirth(jTextForDateOfBirth.getText());
        Person person = new Person(jTextForFirstName.getText(), jTextForLastName.getText(), jTextForPassport.getText(), dateOfBirth);
        Stuff stuff = new Stuff(person, jTextForEmail.getText(), jTextForID.getText(),stuffTypeString,passTextOriginal);
        stuff.addStuff();
        jTextForMessages.setText("Stuff Added Successfully");
        }
         makeFormEmpty();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonForBack;
    private javax.swing.JButton buttonForCreate;
    private javax.swing.JButton buttonForDelete;
    private javax.swing.JButton buttonForSearch;
    private javax.swing.JButton buttonForShowAllStuff;
    private javax.swing.JButton buttonForUpdate;
    private javax.swing.JLabel dateFormatLabel;
    private javax.swing.JTable infoTable;
    private javax.swing.JComboBox<String> jComboToSelecType;
    private javax.swing.JLabel jLabelForMessages;
    private javax.swing.JLabel jLabelForPassword;
    private javax.swing.JLabel jLabelForPasswordConfirm;
    private javax.swing.JLabel jLabelForStuffType;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPassFieldForPassword;
    private javax.swing.JPasswordField jPasswordFieldForPassworkConfirm;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextForDateOfBirth;
    private javax.swing.JTextField jTextForEmail;
    private javax.swing.JTextField jTextForFirstName;
    private javax.swing.JTextField jTextForID;
    private javax.swing.JTextField jTextForLastName;
    private javax.swing.JTextField jTextForMessages;
    private javax.swing.JTextField jTextForPassport;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel labelForDateOfBirth;
    private javax.swing.JLabel labelForEmail;
    private javax.swing.JLabel labelForID;
    private javax.swing.JLabel labelForLastName;
    private javax.swing.JLabel labelForPassportNumber;
    private javax.swing.JLabel labelForRirstName;
    // End of variables declaration//GEN-END:variables
}
